# Comment on first issue:
newIssueWelcomeComment: >
  Hello! ğŸ‘‹ Thanks for opening your first issue here!

# Comment on first PR:
newPRWelcomeComment: >
  Hello! ğŸ‘‹ Thanks for opening your first pull request here!

# Comment on first PR merged:
firstPRMergeComment: >
  ğŸ‰ Congrats on merging your first pull request! ğŸ¥³
